version: "3.7"

services:
  rentit-python:
    build:
      context: .
      dockerfile: Dockerfile.python
    restart: always

  rentit-golang:
    build:
      context: .
      dockerfile: Dockerfile.golang
    restart: always
